name: teste-escola
recipe: laravel

config:
  webroot: backend/public
  php: '8.2'
  database: mysql:8.0

services:
  # 1. Container do PHP
  appserver:
    type: php:8.2

  # 2. Container do MySQL
  database:
    type: mysql:8.0
    portforward: true

  # 3. Container do Node
  node:
    type: node:20
    overrides:
      ports:
        - "5173:5173"

tooling:
  composer:
    service: appserver
  artisan:
    service: appserver
  npm:
    service: node
  node:
    service: node